import React, { useState, useEffect } from "react";

import { FormField, Loader, Card } from "../components";

const RenderCard = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }

  return (
    <h2 className="mt-5 font-bold text-xl uppercase text-[#6449ff]">{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPost, setallPost] = useState(null);
  const [searchText, setSearchText] = useState("");
  const [searchedResults, setSearchedResults] = useState(null);
  const [searchTimeout, setSearchTimeout] = useState(null);

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);

      try {
      
      
        const response = await fetch("https://pixelmind-project-4aeo.vercel.app/api/post");

        if (response.ok) {
          const result = await response.json();
  setallPost(result.posts.reverse());
        }
      } catch (error) {
        alert(error);
      } finally {
        setLoading(false);
      }
    };

    fetchPosts();
  }, []);

  const handleSearchChange = (e) => {
    const text = e.target.value;
    setSearchText(text);

    clearTimeout(searchTimeout);

    const timeout = setTimeout(() => {
      const results = allPost.filter(
        (item) =>
          item.name.toLowerCase().includes(text.toLowerCase()) ||
          item.prompt.toLowerCase().includes(text.toLowerCase())
      );

      setSearchedResults(results);
    }, 500);

    setSearchTimeout(timeout);
  };

  return (
    <section className="max-w-7xl max-auto">
      <div>
        <h1 className="font-extrabold  text-[#222328]  text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[700px] ">
          Browse through a collection of imaginative and visullay stunning
          images Generated by Open - AI{" "}
        </p>
      </div>

      <div className="mt-16">
        <FormField
        
        type="text"
        name="text"
        placeholder="Search Posts "
        value={searchText}
        handleChange={handleSearchChange}
        />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75]   text-xl mb-3">
                {" "}
                Showing result for{" "}
                <span className="text-[#222328]"> {searchText} </span>{" "}
              </h2>
            )}
          </>
        )}
      </div>

      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
      {/* <div class="columns-1 sm:columns-2 md:columns-3 lg:columns-4 gap-4"> */}
        {searchText ? (
          <RenderCard data={searchedResults} title="No Search Result Found" />
        ) : (
          <RenderCard data={allPost} title="No post found" />
        )}
      </div>
    </section>
  );
};

export default Home;
